[workspace]
resolver = "3"
members = ["copypatch", "taxon", "weavy"]
exclude = ["fable"]

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/weavy"
homepage = "https://github.com/bearcove/weavy"

[workspace.dependencies]
blake3 = { version = "1", default-features = false }
copypatch = { path = "copypatch", version = "0.2.0-rc.4" }
facet = { git = "https://github.com/facet-rs/facet", rev = "dc57e24e381f0c61b4acfa242c368656a84348d4" }
facet-core = { git = "https://github.com/facet-rs/facet", rev = "dc57e24e381f0c61b4acfa242c368656a84348d4" }
object = "0.39"
snark = { git = "https://github.com/bearcove/snark", rev = "5b83968ae06d439c8c9ecce5550803acf723c641" }
snark-dsl = { git = "https://github.com/bearcove/snark", rev = "5b83968ae06d439c8c9ecce5550803acf723c641" }
weavy = { path = "weavy", version = "0.2.2" }

[patch."https://github.com/bearcove/weavy"]
copypatch = { path = "copypatch" }
taxon = { path = "taxon" }
weavy = { path = "weavy" }

[patch.crates-io]
copypatch = { path = "copypatch" }
taxon = { path = "taxon" }
weavy = { path = "weavy" }


[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(facet_no_doc)", "cfg(kani)"] }

[workspace.lints.clippy]
disallowed_methods = "deny"

[profile.dev.package.weavy]
opt-level = 2

[profile.dev.package.blake3]
opt-level = 3
